### ISSUE TITLE
list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by PkuRainBow** [CSAILVision/semantic-segmentation-pytorch#41]
![image](https://user-images.githubusercontent.com/4639578/38664512-7027e2fa-3e6c-11e8-9c65-d58b2dc66457.png)

Could you help me about this issue?

**Comment by Tete-Xiao** [comment]
It is because you are using only one GPU to train the model.

The codes are tricky when you have to make it compatible with one-gpu training. You can refer to eval.py to find some insights about how it can be adjusted. 

But anyway, you will definitely not get any reasonable results with only one GPU. So my recommendation is that try to run the model on more GPUs, e.g., 4 or 8.
