### ISSUE TITLE
Usage of segm_downsampling_rate

### ISSUE THREAD

**Issue by sshaoshuai** [CSAILVision/semantic-segmentation-pytorch#62]
Hi, 
Thanks for your codes. 
My question is, can I change the parameter segm_downsampling_rate if I want to use the original size of seg_label? 
I tried it but maybe the decoder network is fixed to output downsample 8x of seg_label.
Could you share any advice to use original size of seg_label?

Thanks very much.

**Comment by hangzhaomit** [comment]
As a matter of fact, the encoder network downsamples the input 8x after passing through all the layers, and then an upsampling layer is used to match the size of seg_label.
You can definitely use larger size of seg_label (4x, 2x, 1x), but it does not make much difference because the outputs are interpolated during training. The downside is larger memory consumption.

**Comment by alanyannick** [comment]
Okay, I will check.
Thanks for your kind help.
