### ISSUE TITLE
can't visit http://sceneparsing.csail.mit.edu/model/

### ISSUE THREAD

**Issue by boundles** [CSAILVision/semantic-segmentation-pytorch#68]
Hi, I want to download resnet101 pretrained model, but the url can't be visited?

**Comment by xmengli999** [comment]
I encounter the same case. ANy solution?

**Comment by hangzhaomit** [comment]
Hi, our server is under regular maintenance today, it will be back tomorrow. Sorry about that.

**Comment by boundles** [comment]
ok, tks.

**Comment by albertchristianto** [comment]
Hi, @hangzhaomit, When usually we can downlolad the pretrained model because I have tried to download it every day, but always can't connect? Right now I am in taiwan (+8 GMT) and since I always tried to download it in the evening (taiwan time), I wonder this problem occurred because your server is in under maintenance daily?
